# Generated by Django 4.2.1 on 2023-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_album', models.CharField(max_length=100)),
                ('Groupe_chanteur', models.CharField(max_length=100)),
                ('annee', models.DateField(blank=True, null=True)),
                ('nbr_titre', models.IntegerField(blank=True)),
            ],
        ),
    ]
