# Generated by Django 4.2.1 on 2023-05-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_acheteur', models.CharField(max_length=100)),
                ('Nbr_album', models.CharField(max_length=100)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('Prix_total', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='albums',
            name='Acheter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='album.acheter'),
        ),
    ]
